markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name: Quincy                                         # 博客名称
    description: 独行的人走得最快！                         # 博客描述
    title: Quincy                                        # 网页标题
    url: http://zhengqinyu.github.io                    # 博客地址
    duoshuo: huanzhen                                    # 多说ID
    tongji: 06bf0c7f3dfe803fd53db62b4a40b627             # 百度统计ID
    zhanzhang: ESiMD8yRf2                                #百度站长
    qiniu: http://7tsy3b.com1.z0.glb.clouddn.com         # 七牛云地址
author:
    name: Quincy                                    # 作者名称
    email: 6601360zqy@gmail.com                             # 邮箱地址
    weibo: http://weibo.com/2741705322                   # 微博地址
    github: https://github.com/ZhengQinyu               # GitHub地址